runtime: python39 # or another supported version
entrypoint: gunicorn -b :$PORT main:app --timeout 1200
service: classify-data
instance_class: F4

automatic_scaling:
  max_instances: 2

runtime_config:
  python_version: 3